version: '3'
services:
  rabbitmq:
    image: "rabbitmq:management"    
    hostname: "rabbit"
    ports:
      - "15672:15672"  
      - "5672:5672"      
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq  
